# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
            ],
            options={
                'verbose_name': '\u9898\u76ee\u5206\u7c7b',
                'verbose_name_plural': '\u9898\u76ee\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('start_date', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_date', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d5b\u4e8b',
                'verbose_name_plural': '\u8d5b\u4e8b',
            },
        ),
        migrations.CreateModel(
            name='ContestJudgeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(verbose_name='\u4efb\u52a1ID')),
                ('status', models.CharField(max_length=255, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('used_time', models.IntegerField(verbose_name='\u8fd0\u884c\u65f6\u95f4')),
                ('used_memory', models.IntegerField(verbose_name='\u4f7f\u7528\u5185\u5b58')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.Contest', verbose_name='\u8d5b\u4e8b')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u5b66\u9662')),
                ('major', models.CharField(max_length=255, verbose_name='\u4e13\u4e1a')),
                ('_class', models.CharField(max_length=255, verbose_name='\u73ed\u7ea7')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='\u6d88\u606f')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u63a8\u9001',
                'verbose_name_plural': '\u6d88\u606f\u63a8\u9001',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
            ],
            options={
                'verbose_name': '\u4f5c\u4e1a',
                'verbose_name_plural': '\u4f5c\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('input_description', models.TextField(verbose_name='\u8f93\u5165\u63cf\u8ff0')),
                ('output_description', models.TextField(verbose_name='\u8f93\u51fa\u63cf\u8ff0')),
                ('sample_input', models.TextField(verbose_name='\u6837\u4f8b\u8f93\u5165')),
                ('sample_output', models.TextField(verbose_name='\u6837\u4f8b\u8f93\u51fa')),
                ('hint', models.TextField(blank=True, verbose_name='\u63d0\u793a')),
                ('input', models.TextField(verbose_name='\u95ee\u9898\u8f93\u5165')),
                ('output', models.TextField(verbose_name='\u95ee\u9898\u8f93\u51fa')),
                ('time_limit', models.IntegerField(help_text='MS', verbose_name='\u65f6\u95f4\u9650\u5236')),
                ('memory_limit', models.IntegerField(help_text='MB', verbose_name='\u5185\u5b58\u9650\u5236')),
            ],
            options={
                'verbose_name': '\u9898\u76ee',
                'verbose_name_plural': '\u9898\u76ee',
            },
        ),
        migrations.CreateModel(
            name='ProblemJudgeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(verbose_name='\u4efb\u52a1ID')),
                ('status', models.CharField(max_length=255, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('used_time', models.IntegerField(verbose_name='\u8fd0\u884c\u65f6\u95f4')),
                ('used_memory', models.IntegerField(verbose_name='\u4f7f\u7528\u5185\u5b58')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.Problem', verbose_name='\u9898\u76ee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u4ea4\u7528\u6237')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255, unique=True, verbose_name='\u5b66\u53f7')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(max_length=255, verbose_name='\u6027\u522b')),
                ('identity', models.CharField(max_length=255, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.Department', verbose_name='\u5b66\u9662')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u4fe1\u606f',
                'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='homework',
            name='receiver',
            field=models.ManyToManyField(to='onlineJudge.Department', verbose_name='\u63a5\u6536\u8005'),
        ),
        migrations.AddField(
            model_name='contestjudgetask',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.Problem', verbose_name='\u9898\u76ee'),
        ),
        migrations.AddField(
            model_name='contestjudgetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u4ea4\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='category',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee\u5217\u8868'),
        ),
    ]
