# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='total_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='total_submit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='problems',
            field=models.ManyToManyField(to='onlineJudge.Problem', verbose_name='\u9898\u76ee'),
        ),
    ]
