# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0002_auto_20171202_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='total_accepted',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='total_submit',
        ),
    ]
