# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0003_auto_20171202_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', verbose_name='\u95ee\u9898\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
