# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0004_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestjudgetask',
            name='task_id',
            field=models.UUIDField(auto_created=True, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='problemjudgetask',
            name='task_id',
            field=models.UUIDField(auto_created=True, verbose_name='\u4efb\u52a1ID'),
        ),
    ]
