# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0005_auto_20171203_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestjudgetask',
            name='code',
            field=models.TextField(default='', verbose_name='\u4ee3\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestjudgetask',
            name='lang',
            field=models.CharField(default='', max_length=255, verbose_name='\u8bed\u8a00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemjudgetask',
            name='code',
            field=models.TextField(default='', verbose_name='\u4ee3\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemjudgetask',
            name='lang',
            field=models.CharField(default='', max_length=255, verbose_name='\u8bed\u8a00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestjudgetask',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='contestjudgetask',
            name='used_memory',
            field=models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='contestjudgetask',
            name='used_time',
            field=models.IntegerField(default=0, verbose_name='\u8fd0\u884c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='problemjudgetask',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='problemjudgetask',
            name='used_memory',
            field=models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='problemjudgetask',
            name='used_time',
            field=models.IntegerField(default=0, verbose_name='\u8fd0\u884c\u65f6\u95f4'),
        ),
    ]
