# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineJudge', '0006_auto_20171203_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submit', models.IntegerField(default=0)),
                ('ac_submit', models.IntegerField(default=0)),
                ('solved_count', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
