# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0007_userranklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
    ]
