# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0009_auto_20171208_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestjudgetask',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='problemjudgetask',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='_class',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u5b66\u9662'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sno',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='\u5b66\u53f7'),
        ),
    ]
